[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "/bin/sh -c '/calcom/node_modules/.bin/prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma && /calcom/scripts/start.sh'"
